### ISSUE TITLE
Add an option to stop on fail

### ISSUE THREAD

**Issue by TomVanGreevenbroek** [BESTSELLER/dev-setup-macos#9]
Hi, 
I've recently have installed everything on a macbook but did have some struggles getting this to work, mainly I think because of this line:
https://github.com/BESTSELLER/dev-setup-macos/blob/fae1d6b6b7b8f932014a7255315af16b855d4c71/install.sh#L3

Since the macbook already came with some of these apps, this would then fail with the .Brewfile. Could we add a condition to it that we can specify if we want it to stop on first fail and maybe keep the window open afterwards, so we can see the errors before it closes and even ignore those 

I'm very new to this Mac OS environment, but hope it will help the next developer and the issue is clear 😄

**Comment by Gaardsholt** [comment]
This script was made for us internally, and it was never really meant to be used by anyone else.
So when you run this script, you are on your own ;)
